version: "3.9"
services:
  api:
    build: ../server
    ports: ["8000:8000"]
    environment:
      - CARRYON_DB_URL=sqlite:///data/carryon.db
    volumes:
      - ../server/data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload